43 neveikia irankiu pastatymas lokacija nustacius rankiniu budu
AplinkosMinisterija/biip-zvejyba-web pull request #50
Opened 2023-12-13 11:33 UTC by LWangllix

2024-01-23 11:28 UTC, DovMa requested changes

2024-01-23 11:28 UTC, DovMa commented on src/components/cards/FishingCard.tsx
> +        .reduce((acc: any, current: any) => acc + Number(current), 0) || '';
Sutvarkius tipus nereiketu tikriausia castint. Dabar visur any sudeta.

2024-01-23 11:28 UTC, DovMa commented on src/components/cards/FishingCard.tsx
> +      .reduce((acc: any, current: any) => acc + Number(current), 0) || '';
Sutvarkius tipus nereiketu tikriausia castint. Dabar visur any sudeta.

2024-01-23 11:28 UTC, DovMa commented on src/components/cards/TimeLineItem.tsx
> +  const sum = weights.reduce((partialSum: number = 0, val: number) => partialSum + Number(val), 0);
val tipas ir taip number, kodel cia reikia castint?

2024-01-23 11:28 UTC, DovMa commented on src/utils/api.ts
>        id: id.toString(),
jeigu id tipas ir taip stringas tai .toString() jau nebereikia

2024-01-23 11:28 UTC, DovMa commented on src/utils/hooks.ts
> +  const errorHandler = ({ code }: any) => {
butu gerai aprasyti tipa

2024-01-23 12:14 UTC, LWangllix commented on src/components/cards/TimeLineItem.tsx
> +  const sum = weights.reduce((partialSum: number = 0, val: number) => partialSum + Number(val), 0);
atrodo iš backendo kažkodėl pareidavo , kai kurie su type string

2024-01-23 12:14 UTC, LWangllix commented on src/components/cards/FishingCard.tsx
> +      .reduce((acc: any, current: any) => acc + Number(current), 0) || '';
Ok, galėsiu sutvarkyt, bet man atrodo iš backendo kiti pareina su "string" tipu, tai konvertavau

2024-01-23 12:14 UTC, LWangllix commented on src/components/cards/FishingCard.tsx
> +        .reduce((acc: any, current: any) => acc + Number(current), 0) || '';
Ok, galėsiu sutvarkyt, bet man atrodo iš backendo kiti pareina su "string" tipu, tai konvertavau

2024-01-23 15:39 UTC, DovMa commented on src/components/cards/TimeLineItem.tsx
> +  const sum = weights.reduce((partialSum: number = 0, val: number) => partialSum + Number(val), 0);
Sitie duomenys duomenu bazej saugomi  kaip json objektas  ir nera validacijos kad siustu tik numberius. Reikia padaryti backende validacija kad leistu tik numberius saugoti. Bet tokiu atveju, kazkur frontende atsiras erroras saugant duomenis. Tai butu gerai rasti  kur siunciamas i backenda stringas ir ten castint. Tada padarius validacija backende cia nebereikes taisyti.

2024-01-23 18:58 UTC, LWangllix commented on src/components/cards/TimeLineItem.tsx
> +  const sum = weights.reduce((partialSum: number = 0, val: number) => partialSum + Number(val), 0);
okei, kai pataisyti backende pasakyk, pafixinsiu cia .

2024-01-24 11:31 UTC, DovMa commented on src/components/cards/TimeLineItem.tsx
> +  const sum = weights.reduce((partialSum: number = 0, val: number) => partialSum + Number(val), 0);
ten biski problematiska, nes ten saugomas ne object[], o {[key: FishType['id']] : number}.  Tai tokiam tipui tai reikia custom validacija daryti. O ir siaip jeigu forma siuncia stringa ir pasitaikis tuscias stringas, tai vistiek bus erroras. Reikia fronte susitvarkyt pries siunciant.

2024-01-24 11:34 UTC, DovMa approved these changes

2024-01-25 21:02 UTC, merged