teksto pataisymas
AplinkosMinisterija/biip-zvejyba-web pull request #67
Opened 2024-04-02 14:29 UTC by DovMa

2024-04-02 19:02 UTC, ambrazasp requested changes

2024-04-02 19:02 UTC, ambrazasp commented on src/components/forms/LocationForm.tsx
> +        Prašome pasirinkti iš sąrašo baro numerį arba įrašykite koordinates.
o kodel istrintas `telkinio pavadinima`? pasirinkime tures buti ir telkiniu pavadinimai ir/arba barai - tai kaip ir sitoje vietoje viskas teisingai buvo

2024-04-03 08:18 UTC, DovMa commented on src/components/forms/LocationForm.tsx
> +        Prašome pasirinkti iš sąrašo baro numerį arba įrašykite koordinates.
Cia tik mariom naudojama, tai manau nereikia.
- Kur zvejosiste?
- Mariose.
- Kokiam vandens telkinyje zvejosite?
- Rubikiu ezere.

Netinka toks variantas, nebent marios dar kokie kiti vandens telkiniai skaitosi.

Kai zvejojama vidaus vandens telkiniuose - tada iskart pasirenkamas vandens telkinys ir ten baru nera.

2024-04-03 08:53 UTC, ambrazasp approved these changes

2024-04-03 08:53 UTC, ambrazasp commented on src/components/forms/LocationForm.tsx
> +        Prašome pasirinkti iš sąrašo baro numerį arba įrašykite koordinates.
supratau

2024-04-03 09:15 UTC, merged